### ISSUE TITLE
On refresh files 

### ISSUE THREAD

**Issue by wolgan09** [pacoita/angular-pwa-boilerplate#11] opened 2020-09-11 09:33 UTC
When i reloaded the page it showed me this:
[Image]:
![image](https://user-images.githubusercontent.com/14955374/92903247-8b92eb80-f43f-11ea-8ff6-5e84c7777d25.png)

Lost manifest file from the sources, got 404 for favicon in network tab.
Is this the common behaviour of PWA/ browser 
Chrome version - 85.0.4

**Comment by pacoita** [comment] 2020-09-14 19:11
I just erased all the cached data on my side and reloaded the page.

Everything is fetched correctly:

![image](https://user-images.githubusercontent.com/13237093/93127476-489a7780-f6ce-11ea-9823-a191e8968afb.png)

If I access the Application Tab in DevTools and I inspect the cache, I can find my favicon there, with other static assets:

![image](https://user-images.githubusercontent.com/13237093/93127677-a038e300-f6ce-11ea-8997-2fe708f1a3d0.png)

Could you try again (delete completely your local storage from the Application tab, to be sure)?

**Comment by pacoita** [comment] 2020-09-15 10:05
Closing as I tested with different devices and I cannot reproduce the issue.

**Closed as completed by pacoita** 2020-09-15 10:05 UTC

**Comment by wolgan09** [comment] 2020-09-15 10:41
Thanks for your efforts, It was reproduced when i opened the demo page in chrome version 67 and thereafter i updated to Chrome version 85 until i restarted the PC it was showing me the distorted page. 
But since then i its working great. 
Amazing Work!!! 
Best Wishes
